apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namespace: sample-app-dev

nameSuffix: -dev

patches:
- path: deployment_env.yaml
  target:
    kind: Deployment
    name: sample-app
    namespace: sample-app-dev

# patchesStrategicMerge:
# - deployment_env.yaml


# configMapGenerator:
#   - name: app-config
#     literals:
#       - username=demo-user

# secretGenerator:
#   - name: credentials
#     type: Opaque
#     literals:
#       - password=demo
