apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namespace: sample-app

nameSuffix: -dev

patches:
- path: deployment_env.yaml

# patchesStrategicMerge:
# - deployment_env.yaml


# configMapGenerator:
#   - name: app-config
#     literals:
#       - username=demo-user

# secretGenerator:
#   - name: credentials
#     type: Opaque
#     literals:
#       - password=demo
