nest-service:
  replicaCount: 1
  configmap:
    PARAMETER_1: "parameter 1"
  service:
    port: 3000
  # livenessProbe:
  #   initialDelaySeconds: 30
  #   periodSeconds: 15
  #   failureThreshold: 240
  #   enabled: true
  #   path: /health
  # readinessProbe:
  #   periodSeconds: 30
  #   initialDelaySeconds: 120
  #   failureThreshold: 120
  #   enabled: true
  #   path: /health
  image:
    repository: ghcr.io/hendrikstone/argocd_service_playground
    tag: "0.0.1"