---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: sample-app-staging
  source:
    path: config/staging/backend-service
    repoURL: https://github.com/HendrikStone/argocd_playground
    targetRevision: HEAD
    helm:
      releaseName: backend-service
      valueFiles:
        - values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: sample-ns
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
