apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-app
  template:
    spec:
      containers:
      - name: backend-app
        image: ghcr.io/hendrikstone/argocd_service_playground:v0.0.5
        env:
        - name: key
          value: dev
#        envFrom:
#        - configMapRef:
#            name: app-config
#        - secretRef:
#            name: credentials
